services:
  db:
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - POSTGRES_DB=ulstu_diploma
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
