"""empty message

Revision ID: 3448cdd92008
Revises: a1eb6130164f
Create Date: 2025-02-27 16:42:53.289168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3448cdd92008"
down_revision: Union[str, None] = "a1eb6130164f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Sample", sa.Column("preset_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "Sample", "Preset", ["preset_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Sample", type_="foreignkey")
    op.drop_column("Sample", "preset_id")
    # ### end Alembic commands ###
