"""empty message

Revision ID: 42c25818003f
Revises: 561dc9f7e602
Create Date: 2025-02-27 22:42:22.815045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42c25818003f"
down_revision: Union[str, None] = "561dc9f7e602"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("Sample", sa.Column("note_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "Sample", "Notes", ["note_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Sample", type_="foreignkey")
    op.drop_column("Sample", "note_id")
    op.drop_table("Notes")
    # ### end Alembic commands ###
