"""empty message

Revision ID: c4b930d43f68
Revises: 42c25818003f
Create Date: 2025-02-27 22:53:37.248178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4b930d43f68"
down_revision: Union[str, None] = "42c25818003f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uniq_notes_for_preset", "Sample", ["preset_id", "note_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uniq_notes_for_preset", "Sample", type_="unique")
    # ### end Alembic commands ###
